[package]
name = "advent-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
itertools = "0.11.0"
regex = "1.9.1"
thousands = "0.2.0"
